@PriceListApi_HostAddress = http://localhost:5295

### Products

GET {{PriceListApi_HostAddress}}/api/product
Accept: application/json

###

GET {{PriceListApi_HostAddress}}/api/product/1
Accept: application/json

###

POST {{PriceListApi_HostAddress}}/api/product
Content-Type: application/json

{
  "productID": 1,
  "productName": "Widget",
  "price": 9.99,
  "quantity": 100,
  "sellerID": 1
}

### Sellers

GET {{PriceListApi_HostAddress}}/api/seller
Accept: application/json

###

POST {{PriceListApi_HostAddress}}/api/seller
Content-Type: application/json

{
  "sellerID": 1,
  "sellerName": "Acme Corp",
  "city": "Cairo"
}

###
